# Generated by Django 5.0 on 2024-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_canvasimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvasimage",
            name="predict",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
